#!/usr/bin/with-contenv bash

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

HOME=${GITLAB_HOME}
set -e

cd ${GITLAB_INSTALL_DIR}
${GITLAB_GITALY_INSTALL_DIR}/gitaly ${GITLAB_GITALY_INSTALL_DIR}/config.toml
