#!/usr/bin/with-contenv bash

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

set -e
HOME=${GITLAB_HOME}

cd ${GITLAB_INSTALL_DIR}
bundle exec sidekiq -c {{SIDEKIQ_CONCURRENCY}}
  -C ${GITLAB_INSTALL_DIR}/config/sidekiq_queues.yml
  -e ${RAILS_ENV}
  -t {{SIDEKIQ_SHUTDOWN_TIMEOUT}}
  -P ${GITLAB_INSTALL_DIR}/tmp/pids/sidekiq.pid
  -L ${GITLAB_INSTALL_DIR}/log/sidekiq.log