#!/usr/bin/with-contenv bash

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

set -e
HOME=${GITLAB_HOME}

cd ${GITLAB_INSTALL_DIR}
bundle exec unicorn_rails -c ${GITLAB_INSTALL_DIR}/config/unicorn.rb -E ${RAILS_ENV}

