#!/usr/bin/with-contenv bash

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

set -e
HOME=${GITLAB_HOME}

cd ${GITLAB_INSTALL_DIR}
/usr/local/bin/gitlab-workhorse
  -listenUmask 0
  -listenNetwork tcp
  -listenAddr ":8181"
  -authBackend http://127.0.0.1:8080{{GITLAB_RELATIVE_URL_ROOT}}
  -authSocket ${GITLAB_INSTALL_DIR}/tmp/sockets/gitlab.socket
  -documentRoot ${GITLAB_INSTALL_DIR}/public
  -proxyHeadersTimeout {{GITLAB_WORKHORSE_TIMEOUT}}
  
